### ISSUE TITLE
instance discrimination task 

### ISSUE THREAD

**Issue by CuongNN218** [ku21fan/STR-Fewer-Labels#1]
You mentioned ''we use an instance discrimination task as a pretext task" in your paper. I'm really confuse which task should be used. As I understand, you feed text images to encoder and train MOCO with only Resnet and then frezze resnet and then train with Bilstm and attention. beside that, I'm confuse with the idea that you train full TRBA with moco and I don't know the next step of 2 stages moco training methods. Feel free to correct me if i misunderstood.

**Comment by ku21fan** [comment]
Hello, 

1. pretrain ResNet part of TRBA with MoCo (use pretrain.py). 
You can check the instance discrimination task from [Algorithm1 in MoCo paper](https://arxiv.org/pdf/1911.05722.pdf) or just check our code [self_supervised.py](https://github.com/ku21fan/STR-Fewer-Labels/blob/main/modules/self_supervised.py)
2. train TRBA with initialization by the model pretrained in 1 (only ResNet part, use train.py).

We just uploaded our code.
You can check the process for MoCo, in [model.py](https://github.com/ku21fan/STR-Fewer-Labels/blob/95ac7e0f781509b0adaf1b10085cc287370527a1/model.py#L78-L84), [self_supervised.py](https://github.com/ku21fan/STR-Fewer-Labels/blob/main/modules/self_supervised.py), [pretrain.py](https://github.com/ku21fan/STR-Fewer-Labels/blob/main/pretrain.py), [train.py](https://github.com/ku21fan/STR-Fewer-Labels/blob/95ac7e0f781509b0adaf1b10085cc287370527a1/train.py#L112-L118).

Hope it helps.

Best
