### ISSUE TITLE
Train from checkpoint

### ISSUE THREAD

**Issue by lyminhuit** [ku21fan/STR-Fewer-Labels#11]
Hi, 
I train model on colab, after a while it will be disconnected. I can train again after a few hours, but I have to train again from the author's checkpoint. How can I continue to train from the checkpoint (weight) that I trained last time. 

Thanks!

**Comment by ku21fan** [comment]
Hi, 

When running `train.py`, use this option `--saved_model saved_models/{the folder including your checkpoint}/best_score.pth`. Then your training continues from your last checkpoint.

Hope it helps :)
