### ISSUE TITLE
Unable to open data files

### ISSUE THREAD

**Issue by mariaalfaroc** [ku21fan/STR-Fewer-Labels#12]
Hi!

I'm having trouble opening the data files in this repository. When I try to open them using Microsoft Access, I receive an error message that says "unrecognized database format" (see image attached). How can I solve the problem? Is it possible to download the data in any other format?

Thank you for your help :)

<img width="502" alt="CaptureMaria" src="https://user-images.githubusercontent.com/56754030/228534215-b0b182fb-1aac-4f4f-bade-4a638ed9da47.png">

**Comment by ku21fan** [comment]
Hi, 

They are lmdb datasets, thus you may not able to open with Microsoft Access.

According to [here](https://support.microsoft.com/en-us/office/which-access-file-format-should-i-use-012d9ab3-d14c-479e-b617-be66f9070b41), the `.mdb` file format was used before Access 2007. 
However, it seems different from that of lmdb dataset, even though lmdb dataset also use `.mdb` file format.

To access samples in lmdb datasets, please see [these codes](https://github.com/ku21fan/STR-Fewer-Labels/blob/e6aa817e2eacbf29b3fcd11390d78b1a8f96bf78/dataset.py#L226-L286).

Hope it helps :)
