### ISSUE TITLE
Train CRNN with semi-supervised methods Pseudo Label (PL) miss "saved_model"

### ISSUE THREAD

**Issue by ecnuycxie** [ku21fan/STR-Fewer-Labels#14]
The step "Train CRNN with semi-supervised methods Pseudo Label (PL)" is incomplete as it does not include the required argument "saved_model".

**Comment by ku21fan** [comment]
Hi, 

The step "Train CRNN with semi-supervised methods Pseudo Label (PL)" does not require the argument "saved_model"
Instead, it uses "--model_for_PseudoLabel" 
For example, 
```
CUDA_VISIBLE_DEVICES=0 python3 train.py --model_name CRNN --exp_name CRNN_PL --Aug Crop90-Rot15 \
--semi Pseudo --model_for_PseudoLabel saved_models/CRNN_aug/best_score.pth
```
Please check the [README.md](https://github.com/ku21fan/STR-Fewer-Labels#training)

Best,
Jeonghun
