### ISSUE TITLE
About image input size

### ISSUE THREAD

**Issue by double-fire-0** [ku21fan/STR-Fewer-Labels#16]
Hi, thanks for your great code and dataset!

My question is about the image input size in training. I see the default image input size is 32x100.
I am a newbie in OCR tasks, is this input size a regular input size for ocr model or, did you choose this input size for other reasons?

Since this input size seems to be small for some complex datasets such as COCO-Text

**Comment by ku21fan** [comment]
Hi, 

Yes, 32x100 is a regular input size for OCR models such as CRNN and TRBA.
By the way, other models use other input sizes (32x128, 48x160, 64x256, and so on) nowadays, so you can try other input sizes depending on your datasets.

Best,
