### ISSUE TITLE
Providing a processed dataset

### ISSUE THREAD

**Issue by terryoo** [ku21fan/STR-Fewer-Labels#2]
It is quite impressive research.
Do you plan to provide a processed dataset used for training and validation such as Real-L and Real-U?

**Comment by ku21fan** [comment]
Hello, 

Thank you for your interest :)
We just upload the preprocessed datasets.
Check [data.md](https://github.com/ku21fan/STR-Fewer-Labels/blob/main/data.md)

Best

**Comment by wzl639** [comment]
> It is quite impressive research.
> Do you plan to provide a processed dataset used for training and validation such as Real-L and Real-U?

Holle, Do you get the datasets? Can you sent me? I can not download form there. thanks!

**Comment by Yuliang-Liu** [comment]
@wzl639 The link is in the top written as "Download preprocessed lmdb dataset for traininig and evaluation"

**Comment by wzl639** [comment]
> @wzl639 The link is in the top written as "Download preprocessed lmdb dataset for traininig and evaluation"

ok thanks I have got the datasets
