### ISSUE TITLE
ablation experiment question

### ISSUE THREAD

**Issue by daeing** [ku21fan/STR-Fewer-Labels#5]
Thanks for your excellent work, you have tried a lot of benchmark and ablation experiment, that's very nice of you. and I have a question, I was just wonder if you train the semi- and self supervised model in the same steps (200k)? Because I notice train moco or pseudo label in a larger steps may have a good result. so I was just wondering if you have contrast the result in 200k steps, 300k steps.

**Comment by ku21fan** [comment]
Hello, 

Thank you for your interest in our work :) 

> if you train the semi- and self supervised model in the same steps (200k)?

Yes, I did.

> if you have contrast the result in 200k steps, 300k steps.

Yes, I did. 
In our experiments, it was up to the experimental setting (using augmentation or semi/self-supervised learning). 
Sometimes 200K is better, and sometimes 300K is better. 
We thought that it does not make a significant difference that can change our conclusion.
Thus we used 200K steps for faster training. 

If the number of steps makes a significant difference and insight, 
and if someone can find some law or theory between iteration and performance,
it would be interesting work! 
(we had tried to find some law or theory, but it was not easy to conclude)

Hope it helps :)
best.

**Comment by daeing** [comment]
> Hello,
> 
> Thank you for your interest in our work :)
> 
> > if you train the semi- and self supervised model in the same steps (200k)?
> 
> Yes, I did.
> 
> > if you have contrast the result in 200k steps, 300k steps.
> 
> Yes, I did. In our experiments, it was up to the experimental setting (using augmentation or semi/self-supervised learning). Sometimes 200K is better, and sometimes 300K is better. We thought that it does not make a significant difference that can change our conclusion. Thus we used 200K steps for faster training.
> 
> If the number of steps makes a significant difference and insight, and if someone can find some law or theory between iteration and performance, it would be interesting work! (we had tried to find some law or theory, but it was not easy to conclude)
> 
> Hope it helps :) best.

Many thanks to your reply, I got what you mean, have a nice day.
