### ISSUE TITLE
pretrained-weights of RotNet

### ISSUE THREAD

**Issue by AndiezPham** [ku21fan/STR-Fewer-Labels#8]
It is quite impressive research.
Could you share pretrained-weights of RotNet?
Thanks for your helps!

**Comment by ku21fan** [comment]
Hi, 
Thank you for your interest in our work :)

Yes, I checked the log in 2020~2021, and I just found and uploaded the pretrained-weights of RotNet [here](https://www.dropbox.com/sh/23adceu2i85c4x1/AACLmaiL43Jy8eYIVVUkZ344a?dl=0).
- For CRNN, use CRNN-NV-Pretrain-RotNet.pth
- For TRBA, use TRBA-NR-Pretrain-RotNet.pth 

Hope it helps :)

Best
